FROM alpine:3

LABEL author="Koko Yuardi"
LABEL campus="Institut Teknologi Kalimantan" website="https://itk.ac.id/"

RUN mkdir hello
RUN echo "Hello World" > "hello/world.txt"

CMD cat "hello/world.txt"